export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          persona: 'creator' | 'founder' | 'coach' | 'local_business' | 'agency';
          demo_mode: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          persona?: 'creator' | 'founder' | 'coach' | 'local_business' | 'agency';
          demo_mode?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          full_name?: string | null;
          persona?: 'creator' | 'founder' | 'coach' | 'local_business' | 'agency';
          demo_mode?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string | null;
          org_type: 'solo' | 'agency' | 'company';
          plan_key: string;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug?: string | null;
          org_type?: 'solo' | 'agency' | 'company';
          plan_key?: string;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          slug?: string | null;
          org_type?: 'solo' | 'agency' | 'company';
          plan_key?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      organization_memberships: {
        Row: {
          id: string;
          org_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer' | 'billing_admin';
          status: 'active' | 'invited' | 'suspended';
          invited_by: string | null;
          joined_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          user_id: string;
          role?: 'owner' | 'admin' | 'editor' | 'viewer' | 'billing_admin';
          status?: 'active' | 'invited' | 'suspended';
          invited_by?: string | null;
          joined_at?: string | null;
          created_at?: string;
        };
        Update: {
          role?: 'owner' | 'admin' | 'editor' | 'viewer' | 'billing_admin';
          status?: 'active' | 'invited' | 'suspended';
          joined_at?: string | null;
        };
        Relationships: [];
      };
      business_dna: {
        Row: {
          id: string;
          org_id: string;
          website_url: string | null;
          contact_phone: string | null;
          contact_email: string | null;
          mission: string | null;
          vision: string | null;
          positioning: string | null;
          brand_voice: string | null;
          ideal_customer_profile: string | null;
          products_services: string | null;
          faqs: string | null;
          pricing: string | null;
          offers: string | null;
          competitors: string | null;
          brand_assets: string | null;
          sales_scripts: string | null;
          policies: string | null;
          website_summary: string | null;
          social_links: string | null;
          values: string | null;
          audience: string | null;
          proof_points: string | null;
          growth_goal: string | null;
          key_metric: string | null;
          additional_notes: string | null;
          brand_colors: Json;
          logo_storage_bucket: string | null;
          logo_storage_path: string | null;
          logo_file_name: string | null;
          logo_mime_type: string | null;
          logo_size_bytes: number | null;
          logo_alt_text: string | null;
          qr_storage_bucket: string | null;
          qr_storage_path: string | null;
          qr_file_name: string | null;
          qr_mime_type: string | null;
          qr_size_bytes: number | null;
          qr_alt_text: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          website_url?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          mission?: string | null;
          vision?: string | null;
          positioning?: string | null;
          brand_voice?: string | null;
          ideal_customer_profile?: string | null;
          products_services?: string | null;
          faqs?: string | null;
          pricing?: string | null;
          offers?: string | null;
          competitors?: string | null;
          brand_assets?: string | null;
          sales_scripts?: string | null;
          policies?: string | null;
          website_summary?: string | null;
          social_links?: string | null;
          values?: string | null;
          audience?: string | null;
          proof_points?: string | null;
          growth_goal?: string | null;
          key_metric?: string | null;
          additional_notes?: string | null;
          brand_colors?: Json;
          logo_storage_bucket?: string | null;
          logo_storage_path?: string | null;
          logo_file_name?: string | null;
          logo_mime_type?: string | null;
          logo_size_bytes?: number | null;
          logo_alt_text?: string | null;
          qr_storage_bucket?: string | null;
          qr_storage_path?: string | null;
          qr_file_name?: string | null;
          qr_mime_type?: string | null;
          qr_size_bytes?: number | null;
          qr_alt_text?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          website_url?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          mission?: string | null;
          vision?: string | null;
          positioning?: string | null;
          brand_voice?: string | null;
          ideal_customer_profile?: string | null;
          products_services?: string | null;
          faqs?: string | null;
          pricing?: string | null;
          offers?: string | null;
          competitors?: string | null;
          brand_assets?: string | null;
          sales_scripts?: string | null;
          policies?: string | null;
          website_summary?: string | null;
          social_links?: string | null;
          values?: string | null;
          audience?: string | null;
          proof_points?: string | null;
          growth_goal?: string | null;
          key_metric?: string | null;
          additional_notes?: string | null;
          brand_colors?: Json;
          logo_storage_bucket?: string | null;
          logo_storage_path?: string | null;
          logo_file_name?: string | null;
          logo_mime_type?: string | null;
          logo_size_bytes?: number | null;
          logo_alt_text?: string | null;
          qr_storage_bucket?: string | null;
          qr_storage_path?: string | null;
          qr_file_name?: string | null;
          qr_mime_type?: string | null;
          qr_size_bytes?: number | null;
          qr_alt_text?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_business_dna: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          website_url: string | null;
          contact_phone: string | null;
          contact_email: string | null;
          mission: string | null;
          vision: string | null;
          positioning: string | null;
          brand_voice: string | null;
          ideal_customer_profile: string | null;
          products_services: string | null;
          faqs: string | null;
          pricing: string | null;
          offers: string | null;
          competitors: string | null;
          brand_assets: string | null;
          sales_scripts: string | null;
          policies: string | null;
          website_summary: string | null;
          social_links: string | null;
          values: string | null;
          audience: string | null;
          proof_points: string | null;
          growth_goal: string | null;
          key_metric: string | null;
          additional_notes: string | null;
          brand_colors: Json;
          logo_storage_bucket: string | null;
          logo_storage_path: string | null;
          logo_file_name: string | null;
          logo_mime_type: string | null;
          logo_size_bytes: number | null;
          logo_alt_text: string | null;
          qr_storage_bucket: string | null;
          qr_storage_path: string | null;
          qr_file_name: string | null;
          qr_mime_type: string | null;
          qr_size_bytes: number | null;
          qr_alt_text: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          website_url?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          mission?: string | null;
          vision?: string | null;
          positioning?: string | null;
          brand_voice?: string | null;
          ideal_customer_profile?: string | null;
          products_services?: string | null;
          faqs?: string | null;
          pricing?: string | null;
          offers?: string | null;
          competitors?: string | null;
          brand_assets?: string | null;
          sales_scripts?: string | null;
          policies?: string | null;
          website_summary?: string | null;
          social_links?: string | null;
          values?: string | null;
          audience?: string | null;
          proof_points?: string | null;
          growth_goal?: string | null;
          key_metric?: string | null;
          additional_notes?: string | null;
          brand_colors?: Json;
          logo_storage_bucket?: string | null;
          logo_storage_path?: string | null;
          logo_file_name?: string | null;
          logo_mime_type?: string | null;
          logo_size_bytes?: number | null;
          logo_alt_text?: string | null;
          qr_storage_bucket?: string | null;
          qr_storage_path?: string | null;
          qr_file_name?: string | null;
          qr_mime_type?: string | null;
          qr_size_bytes?: number | null;
          qr_alt_text?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          website_url?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          mission?: string | null;
          vision?: string | null;
          positioning?: string | null;
          brand_voice?: string | null;
          ideal_customer_profile?: string | null;
          products_services?: string | null;
          faqs?: string | null;
          pricing?: string | null;
          offers?: string | null;
          competitors?: string | null;
          brand_assets?: string | null;
          sales_scripts?: string | null;
          policies?: string | null;
          website_summary?: string | null;
          social_links?: string | null;
          values?: string | null;
          audience?: string | null;
          proof_points?: string | null;
          growth_goal?: string | null;
          key_metric?: string | null;
          additional_notes?: string | null;
          brand_colors?: Json;
          logo_storage_bucket?: string | null;
          logo_storage_path?: string | null;
          logo_file_name?: string | null;
          logo_mime_type?: string | null;
          logo_size_bytes?: number | null;
          logo_alt_text?: string | null;
          qr_storage_bucket?: string | null;
          qr_storage_path?: string | null;
          qr_file_name?: string | null;
          qr_mime_type?: string | null;
          qr_size_bytes?: number | null;
          qr_alt_text?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      analytics_sources: {
        Row: {
          id: string;
          org_id: string;
          source_key: string;
          display_name: string;
          category: 'ads' | 'social' | 'ecommerce' | 'web' | 'email' | 'crm' | 'other';
          status: 'connected' | 'syncing' | 'disconnected' | 'error';
          external_account_id: string | null;
          last_synced_at: string | null;
          metadata: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          source_key: string;
          display_name: string;
          category?: 'ads' | 'social' | 'ecommerce' | 'web' | 'email' | 'crm' | 'other';
          status?: 'connected' | 'syncing' | 'disconnected' | 'error';
          external_account_id?: string | null;
          last_synced_at?: string | null;
          metadata?: Json;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          source_key?: string;
          display_name?: string;
          category?: 'ads' | 'social' | 'ecommerce' | 'web' | 'email' | 'crm' | 'other';
          status?: 'connected' | 'syncing' | 'disconnected' | 'error';
          external_account_id?: string | null;
          last_synced_at?: string | null;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      analytics_metrics: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          source_key: string;
          campaign: string;
          metric_date: string;
          spend: number;
          impressions: number;
          clicks: number;
          conversions: number;
          revenue: number;
          metadata: Json;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          source_key: string;
          campaign?: string;
          metric_date: string;
          spend?: number;
          impressions?: number;
          clicks?: number;
          conversions?: number;
          revenue?: number;
          metadata?: Json;
          created_by: string;
          created_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          source_key?: string;
          campaign?: string;
          metric_date?: string;
          spend?: number;
          impressions?: number;
          clicks?: number;
          conversions?: number;
          revenue?: number;
          metadata?: Json;
        };
        Relationships: [];
      };
      campaigns: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          name: string;
          type: 'standard' | 'influencer' | 'ads' | 'launch' | 'evergreen';
          status: 'draft' | 'active' | 'paused' | 'completed' | 'archived';
          objective: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          name: string;
          type?: 'standard' | 'influencer' | 'ads' | 'launch' | 'evergreen';
          status?: 'draft' | 'active' | 'paused' | 'completed' | 'archived';
          objective?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          name?: string;
          type?: 'standard' | 'influencer' | 'ads' | 'launch' | 'evergreen';
          status?: 'draft' | 'active' | 'paused' | 'completed' | 'archived';
          objective?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      content_items: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          campaign_id: string | null;
          content_type: 'post' | 'poster' | 'video';
          title: string;
          body: string | null;
          media_url: string | null;
          metadata: Json | null;
          status: 'draft' | 'ready' | 'queued' | 'published' | 'archived';
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          content_type?: 'post' | 'poster' | 'video';
          title: string;
          body?: string | null;
          media_url?: string | null;
          metadata?: Json | null;
          status?: 'draft' | 'ready' | 'queued' | 'published' | 'archived';
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          content_type?: 'post' | 'poster' | 'video';
          title?: string;
          body?: string | null;
          media_url?: string | null;
          metadata?: Json | null;
          status?: 'draft' | 'ready' | 'queued' | 'published' | 'archived';
          updated_at?: string;
        };
        Relationships: [];
      };
      marketing_tasks: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          campaign_id: string | null;
          title: string;
          description: string | null;
          task_type: 'publish_reel' | 'launch_meta_ads' | 'send_newsletter' | 'review_google_ads' | 'approve_campaign' | 'custom';
          checklist: Json | null;
          brand_guidelines: string | null;
          attachments: Json | null;
          expected_outputs: string | null;
          status: 'todo' | 'in_progress' | 'blocked' | 'in_review' | 'approved' | 'done' | 'archived';
          assignee: string | null;
          due_at: string | null;
          recurrence: 'none' | 'daily' | 'weekly' | 'monthly';
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          title: string;
          description?: string | null;
          task_type?: 'publish_reel' | 'launch_meta_ads' | 'send_newsletter' | 'review_google_ads' | 'approve_campaign' | 'custom';
          checklist?: Json | null;
          brand_guidelines?: string | null;
          attachments?: Json | null;
          expected_outputs?: string | null;
          status?: 'todo' | 'in_progress' | 'blocked' | 'in_review' | 'approved' | 'done' | 'archived';
          assignee?: string | null;
          due_at?: string | null;
          recurrence?: 'none' | 'daily' | 'weekly' | 'monthly';
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          title?: string;
          description?: string | null;
          task_type?: 'publish_reel' | 'launch_meta_ads' | 'send_newsletter' | 'review_google_ads' | 'approve_campaign' | 'custom';
          checklist?: Json | null;
          brand_guidelines?: string | null;
          attachments?: Json | null;
          expected_outputs?: string | null;
          status?: 'todo' | 'in_progress' | 'blocked' | 'in_review' | 'approved' | 'done' | 'archived';
          assignee?: string | null;
          due_at?: string | null;
          recurrence?: 'none' | 'daily' | 'weekly' | 'monthly';
          updated_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          campaign_id: string | null;
          full_name: string;
          company: string | null;
          email: string | null;
          phone: string | null;
          source: 'manual' | 'website' | 'social' | 'ads' | 'referral' | 'referrals' | 'whatsapp' | 'instagram' | 'facebook' | 'google_forms' | 'imports' | 'comments' | 'dms' | 'campaign' | 'event' | 'other';
          status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | 'archived';
          lead_type: 'hot' | 'warm' | 'cold';
          lead_score: number;
          estimated_value: number | null;
          next_follow_up_at: string | null;
          notes: string | null;
          external_source_key: string | null;
          external_lead_id: string | null;
          metadata: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          full_name: string;
          company?: string | null;
          email?: string | null;
          phone?: string | null;
          source?: 'manual' | 'website' | 'social' | 'ads' | 'referral' | 'referrals' | 'whatsapp' | 'instagram' | 'facebook' | 'google_forms' | 'imports' | 'comments' | 'dms' | 'campaign' | 'event' | 'other';
          status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | 'archived';
          lead_type?: 'hot' | 'warm' | 'cold';
          lead_score?: number;
          estimated_value?: number | null;
          next_follow_up_at?: string | null;
          notes?: string | null;
          external_source_key?: string | null;
          external_lead_id?: string | null;
          metadata?: Json;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          full_name?: string;
          company?: string | null;
          email?: string | null;
          phone?: string | null;
          source?: 'manual' | 'website' | 'social' | 'ads' | 'referral' | 'referrals' | 'whatsapp' | 'instagram' | 'facebook' | 'google_forms' | 'imports' | 'comments' | 'dms' | 'campaign' | 'event' | 'other';
          status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | 'archived';
          lead_type?: 'hot' | 'warm' | 'cold';
          lead_score?: number;
          estimated_value?: number | null;
          next_follow_up_at?: string | null;
          notes?: string | null;
          external_source_key?: string | null;
          external_lead_id?: string | null;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      inbox_threads: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          campaign_id: string | null;
          lead_id: string | null;
          distribution_handle_id: string | null;
          channel: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram' | 'website' | 'email' | 'other';
          contact_name: string;
          contact_email: string | null;
          contact_phone: string | null;
          external_thread_id: string | null;
          status: 'open' | 'pending' | 'replied' | 'resolved' | 'archived';
          priority: 'low' | 'normal' | 'high';
          last_message_preview: string | null;
          last_message_at: string;
          assigned_to: string | null;
          labels: string[];
          lead_detection: Json;
          last_ai_suggestions: Json;
          metadata: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          lead_id?: string | null;
          distribution_handle_id?: string | null;
          channel?: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram' | 'website' | 'email' | 'other';
          contact_name: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          external_thread_id?: string | null;
          status?: 'open' | 'pending' | 'replied' | 'resolved' | 'archived';
          priority?: 'low' | 'normal' | 'high';
          last_message_preview?: string | null;
          last_message_at?: string;
          assigned_to?: string | null;
          labels?: string[];
          lead_detection?: Json;
          last_ai_suggestions?: Json;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          lead_id?: string | null;
          distribution_handle_id?: string | null;
          channel?: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram' | 'website' | 'email' | 'other';
          contact_name?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          external_thread_id?: string | null;
          status?: 'open' | 'pending' | 'replied' | 'resolved' | 'archived';
          priority?: 'low' | 'normal' | 'high';
          last_message_preview?: string | null;
          last_message_at?: string;
          assigned_to?: string | null;
          labels?: string[];
          lead_detection?: Json;
          last_ai_suggestions?: Json;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      inbox_messages: {
        Row: {
          id: string;
          org_id: string;
          thread_id: string;
          direction: 'inbound' | 'outbound' | 'internal';
          body: string;
          sender_name: string | null;
          sender_handle: string | null;
          external_message_id: string | null;
          metadata: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          thread_id: string;
          direction?: 'inbound' | 'outbound' | 'internal';
          body: string;
          sender_name?: string | null;
          sender_handle?: string | null;
          external_message_id?: string | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          direction?: 'inbound' | 'outbound' | 'internal';
          body?: string;
          sender_name?: string | null;
          sender_handle?: string | null;
          external_message_id?: string | null;
          metadata?: Json;
        };
        Relationships: [];
      };
      inbox_reply_templates: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          title: string;
          body: string;
          channel: 'any' | 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram' | 'website' | 'email' | 'other';
          status: 'active' | 'archived';
          metadata: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          title: string;
          body: string;
          channel?: 'any' | 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram' | 'website' | 'email' | 'other';
          status?: 'active' | 'archived';
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          title?: string;
          body?: string;
          channel?: 'any' | 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram' | 'website' | 'email' | 'other';
          status?: 'active' | 'archived';
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      competitors: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          name: string;
          industry: string | null;
          website_url: string | null;
          logo_url: string | null;
          social_accounts: Json;
          status: 'monitoring' | 'paused' | 'archived';
          activity_score: number;
          trend: 'growing' | 'stable' | 'declining' | 'unknown';
          google_rating: number | null;
          running_ads: boolean;
          refresh_schedule: 'manual' | 'daily' | 'weekly' | 'monthly';
          website_snapshot: Json;
          social_snapshot: Json;
          content_snapshot: Json;
          ads_snapshot: Json;
          review_snapshot: Json;
          offer_snapshot: Json;
          seo_snapshot: Json;
          analytics_snapshot: Json;
          ai_insights: Json;
          swot: Json;
          why_winning: Json;
          last_refreshed_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          name: string;
          industry?: string | null;
          website_url?: string | null;
          logo_url?: string | null;
          social_accounts?: Json;
          status?: 'monitoring' | 'paused' | 'archived';
          activity_score?: number;
          trend?: 'growing' | 'stable' | 'declining' | 'unknown';
          google_rating?: number | null;
          running_ads?: boolean;
          refresh_schedule?: 'manual' | 'daily' | 'weekly' | 'monthly';
          website_snapshot?: Json;
          social_snapshot?: Json;
          content_snapshot?: Json;
          ads_snapshot?: Json;
          review_snapshot?: Json;
          offer_snapshot?: Json;
          seo_snapshot?: Json;
          analytics_snapshot?: Json;
          ai_insights?: Json;
          swot?: Json;
          why_winning?: Json;
          last_refreshed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          name?: string;
          industry?: string | null;
          website_url?: string | null;
          logo_url?: string | null;
          social_accounts?: Json;
          status?: 'monitoring' | 'paused' | 'archived';
          activity_score?: number;
          trend?: 'growing' | 'stable' | 'declining' | 'unknown';
          google_rating?: number | null;
          running_ads?: boolean;
          refresh_schedule?: 'manual' | 'daily' | 'weekly' | 'monthly';
          website_snapshot?: Json;
          social_snapshot?: Json;
          content_snapshot?: Json;
          ads_snapshot?: Json;
          review_snapshot?: Json;
          offer_snapshot?: Json;
          seo_snapshot?: Json;
          analytics_snapshot?: Json;
          ai_insights?: Json;
          swot?: Json;
          why_winning?: Json;
          last_refreshed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      competitor_events: {
        Row: {
          id: string;
          org_id: string;
          competitor_id: string;
          event_type: 'website' | 'social' | 'content' | 'ads' | 'reviews' | 'offers' | 'seo' | 'analytics' | 'alert' | 'insight';
          severity: 'info' | 'opportunity' | 'threat' | 'alert';
          title: string;
          details: string | null;
          event_at: string;
          metadata: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          competitor_id: string;
          event_type?: 'website' | 'social' | 'content' | 'ads' | 'reviews' | 'offers' | 'seo' | 'analytics' | 'alert' | 'insight';
          severity?: 'info' | 'opportunity' | 'threat' | 'alert';
          title: string;
          details?: string | null;
          event_at?: string;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          event_type?: 'website' | 'social' | 'content' | 'ads' | 'reviews' | 'offers' | 'seo' | 'analytics' | 'alert' | 'insight';
          severity?: 'info' | 'opportunity' | 'threat' | 'alert';
          title?: string;
          details?: string | null;
          event_at?: string;
          metadata?: Json;
        };
        Relationships: [];
      };
      trend_radar_items: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          campaign_id: string | null;
          source: 'google_trends' | 'instagram' | 'youtube' | 'linkedin' | 'competitor' | 'ai_opportunity' | 'manual' | 'other';
          topic: string;
          signal: string | null;
          change_percent: number;
          confidence_score: number;
          status: 'new' | 'reviewing' | 'approved' | 'campaign_generated' | 'dismissed' | 'archived';
          recommended_campaign: string | null;
          opportunity: string | null;
          source_url: string | null;
          detected_at: string;
          metadata: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          source?: 'google_trends' | 'instagram' | 'youtube' | 'linkedin' | 'competitor' | 'ai_opportunity' | 'manual' | 'other';
          topic: string;
          signal?: string | null;
          change_percent?: number;
          confidence_score?: number;
          status?: 'new' | 'reviewing' | 'approved' | 'campaign_generated' | 'dismissed' | 'archived';
          recommended_campaign?: string | null;
          opportunity?: string | null;
          source_url?: string | null;
          detected_at?: string;
          metadata?: Json;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          campaign_id?: string | null;
          source?: 'google_trends' | 'instagram' | 'youtube' | 'linkedin' | 'competitor' | 'ai_opportunity' | 'manual' | 'other';
          topic?: string;
          signal?: string | null;
          change_percent?: number;
          confidence_score?: number;
          status?: 'new' | 'reviewing' | 'approved' | 'campaign_generated' | 'dismissed' | 'archived';
          recommended_campaign?: string | null;
          opportunity?: string | null;
          source_url?: string | null;
          detected_at?: string;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      social_posts: {
        Row: {
          id: string;
          org_id: string;
          client_business_dna_id: string | null;
          title: string;
          body: string | null;
          media_url: string | null;
          campaign_id: string | null;
          content_item_id: string | null;
          content_type: 'post' | 'poster' | 'video';
          status: 'draft' | 'queued' | 'publishing' | 'published' | 'partial_failed' | 'failed' | 'cancelled';
          scheduled_at: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_business_dna_id?: string | null;
          title: string;
          body?: string | null;
          media_url?: string | null;
          campaign_id?: string | null;
          content_item_id?: string | null;
          content_type?: 'post' | 'poster' | 'video';
          status?: 'draft' | 'queued' | 'publishing' | 'published' | 'partial_failed' | 'failed' | 'cancelled';
          scheduled_at?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          client_business_dna_id?: string | null;
          title?: string;
          body?: string | null;
          media_url?: string | null;
          campaign_id?: string | null;
          content_item_id?: string | null;
          content_type?: 'post' | 'poster' | 'video';
          status?: 'draft' | 'queued' | 'publishing' | 'published' | 'partial_failed' | 'failed' | 'cancelled';
          scheduled_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      publish_targets: {
        Row: {
          id: string;
          org_id: string;
          social_post_id: string;
          distribution_handle_id: string | null;
          provider: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram';
          target_label: string;
          status: 'queued' | 'publishing' | 'published' | 'failed' | 'rate_limited' | 'skipped';
          external_post_id: string | null;
          provider_response: Json;
          error_message: string | null;
          attempts: number;
          last_attempt_at: string | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          social_post_id: string;
          distribution_handle_id?: string | null;
          provider: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram';
          target_label: string;
          status?: 'queued' | 'publishing' | 'published' | 'failed' | 'rate_limited' | 'skipped';
          external_post_id?: string | null;
          provider_response?: Json;
          error_message?: string | null;
          attempts?: number;
          last_attempt_at?: string | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'queued' | 'publishing' | 'published' | 'failed' | 'rate_limited' | 'skipped';
          external_post_id?: string | null;
          provider_response?: Json;
          error_message?: string | null;
          attempts?: number;
          last_attempt_at?: string | null;
          published_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };      social_media_assets: {
        Row: {
          id: string;
          org_id: string;
          social_post_id: string | null;
          media_type: 'poster' | 'video' | 'image' | 'document';
          file_name: string;
          mime_type: string | null;
          size_bytes: number | null;
          storage_bucket: string;
          storage_path: string;
          external_url: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          social_post_id?: string | null;
          media_type: 'poster' | 'video' | 'image' | 'document';
          file_name: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          storage_bucket?: string;
          storage_path: string;
          external_url?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          social_post_id?: string | null;
          media_type?: 'poster' | 'video' | 'image' | 'document';
          file_name?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          storage_path?: string;
          external_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };      distribution_handles: {
        Row: {
          id: string;
          org_id: string;
          integration_account_id: string | null;
          provider: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram';
          handle_type: 'facebook_page' | 'instagram_business' | 'linkedin_page' | 'youtube_channel' | 'google_ads_customer' | 'whatsapp_phone_number' | 'slack_channel' | 'telegram_channel';
          display_name: string;
          external_handle_id: string | null;
          is_enabled: boolean;
          default_for_provider: boolean;
          metadata: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          integration_account_id?: string | null;
          provider: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'google_ads' | 'whatsapp' | 'slack' | 'telegram';
          handle_type: 'facebook_page' | 'instagram_business' | 'linkedin_page' | 'youtube_channel' | 'google_ads_customer' | 'whatsapp_phone_number' | 'slack_channel' | 'telegram_channel';
          display_name: string;
          external_handle_id?: string | null;
          is_enabled?: boolean;
          default_for_provider?: boolean;
          metadata?: Json;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          display_name?: string;
          external_handle_id?: string | null;
          is_enabled?: boolean;
          default_for_provider?: boolean;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };    };
    Views: Record<string, never>;
    Functions: {
      reserve_ai_usage: {
        Args: {
          p_org_id: string;
          p_user_id: string;
          p_action: string;
          p_daily_limit?: number;
        };
        Returns: Json;
      };
      workspace_dashboard_stats: {
        Args: { target_org_id: string };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
